name: Deploy Multi-Account Services

on:
  workflow_dispatch:
    inputs:
      deploy_lb:
        description: 'Deploy Load Balancer'
        required: false
        type: boolean
        default: false
      deploy_backend:
        description: 'Deploy Backend Admin(Main)'
        required: false
        type: boolean
        default: false
      deploy_workers:
        description: 'Deploy Backend Workers'
        required: false
        type: boolean
        default: false
      deploy_admin_frontend:
        description: 'Deploy Admin Frontend (Vercel)'
        required: false
        type: boolean
        default: false
      deploy_website:
        description: 'Deploy Website (Vercel)'
        required: false
        type: boolean
        default: false
      update_dev:
        description: 'Update Dev nodes'
        required: false
        type: boolean
        default: false

jobs:
  trigger-deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Load Balancer
        if: ${{ github.event.inputs.deploy_lb == 'true' }}
        run: |
          echo "Triggering Load Balancer deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_LB }}"

      - name: Deploy Backend Admin(Main)
        if: ${{ github.event.inputs.deploy_backend == 'true' }}
        run: |
          echo "Triggering Admin Backend deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_ADMIN }}"

      - name: Deploy Backend Workers
        if: ${{ github.event.inputs.deploy_workers == 'true' }}
        run: |
          echo "Triggering Worker 1 deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_WORKER_1 }}"

          echo "Triggering Worker 2 deployment..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_WORKER_2 }}"

      - name: Deploy Admin Frontend
        if: ${{ github.event.inputs.deploy_admin_frontend == 'true' }}
        run: |
          echo "Triggering Admin Frontend deployment on Vercel..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_ADMIN_FRONTEND }}"

      - name: Deploy Website
        if: ${{ github.event.inputs.deploy_website == 'true' }}
        run: |
          echo "Triggering Website deployment on Vercel..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_WEBSITE }}"

      - name: Update Dev System
        if: ${{ github.event.inputs.update_dev == 'true'}}
        run: |
          echo "Triggering Dev Backend Update"
          curl -X POST "${{ secrets.RENDER_DEV_BACKEND }}"

          echo "Triggering Dev Frontend Update(Admin-frontend)"
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_DEV_ADMIN_FRONTEND }}"